language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pyrus install -f pear/PHP_CodeSniffer-1.5.4
  - phpenv rehash

script:
#  - phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .
